# Generated by Django 4.0.2 on 2022-02-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.URLField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
